ModelManager integration into ngraph_creator and ops implementations
intel/nn-hal pull request #72
Opened 2021-03-24 12:07 UTC by akodanka

Refactor ngraph_creator for ModelManager Integration.
Add support for Burst Execution, required for vts tests.
Implementation of operations using the new structure.

2021-03-24 12:16 UTC, JaikrishnaNemallapudi approved these changes
lgtm

2021-03-24 12:18 UTC, JaikrishnaNemallapudi approved these changes
LGTM

2021-03-24 12:29 UTC, JaikrishnaNemallapudi approved these changes
LGTM

2021-03-24 12:35 UTC, JaikrishnaNemallapudi approved these changes
LGTM

2021-03-25 09:28 UTC, JeevakaPrabu reviewed
LGTM

2021-03-25 09:32 UTC, JeevakaPrabu requested changes

2021-03-25 09:32 UTC, JeevakaPrabu commented on ngraph_creator/operations/src/OperationsBase.cpp
> +    if(mNgraphNodes->isForcedNchw(inputIndex))
introduce space between if and (

2021-03-25 09:32 UTC, JeevakaPrabu commented on ngraph_creator/src/NgraphNodes.cpp
> +bool NgraphNodes::isForcedNchw(size_t index) {
Validate the index before using with the vector

2021-03-25 09:32 UTC, JeevakaPrabu commented on ngraph_creator/src/NgraphNodes.cpp
> +    mForcedNchw[index] = flag;
same comment as above

2021-03-25 13:00 UTC, rairatne approved these changes
LGTM

2021-03-25 13:01 UTC, rairatne approved these changes
LGTM

2021-03-25 13:03 UTC, rairatne approved these changes
LGTM

2021-03-25 13:05 UTC, rairatne approved these changes
LGTM

2021-03-25 16:17 UTC, lakshmishreec approved these changes
LGTM

2021-03-30 11:19 UTC, RavirajSitaram approved these changes

2021-03-31 12:40 UTC, JaikrishnaNemallapudi commented on IENetwork.cpp
> +    InferenceEngine::Core ie;
Pass plugin.xml path
InferenceEngine::Core ie(std::string("/vendor/etc/openvino/plugins.xml"));

2021-03-31 12:42 UTC, JaikrishnaNemallapudi reviewed
Please add plugin.xml path

2021-04-01 13:26 UTC, merged